import { ProductsItemProps } from '../../types/model';

export default {
	id: 'new',
	type: 'default',
	name: '',
	categories: [],
	tags: [],
	item_price: 0,
	item_discount: 0,
	item_weight: 0,
	item_depth: 0,
	item_height: 0,
	item_width: 0,
	related: [],
	gallery: [],
	attachments: [],
	img_main: '',
	img_thumbnail: '',
	producers: [],
	distributors: [],
	options: [],
	rating: 0,
	manager: 0,
	is_new: true,
	is_used: false,
	is_unboxed: false,
	active: true,
	lang: {},
} as ProductsItemProps;
