<aside id="Sidebar">
    @if($sidebar_widget['search'])
        @include('component.sidebar-search')
    @endif
    @if($sidebar_widget['user'])
        @include('component.sidebar-members')
    @endif
    @if($sidebar_widget['basket'])
        @include('component.sidebar-basket')
    @else
        @include('component.sidebar-basket-tmp')
    @endif
    @if($sidebar_widget['last-posts'])
        @include('component.sidebar-last-posts')
    @endif
    @if($sidebar_widget['subscription'])
        @include('component.sidebar-members-subscribe')
    @endif
</aside>